# Generated by Django 3.0.6 on 2020-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_num', models.IntegerField(default=0, verbose_name='服务对象数')),
                ('request_num', models.IntegerField(default=0, verbose_name='发出请求的房间数')),
                ('state', models.IntegerField(choices=[(1, 'Working'), (2, 'Shutdown')])),
                ('temp_high_limit', models.IntegerField(default=0)),
                ('temp_low_limit', models.IntegerField(default=0)),
                ('default_target_temp', models.IntegerField(default=26)),
                ('fee_rate_h', models.FloatField()),
                ('fee_rate_l', models.FloatField()),
                ('fee_rate_m', models.FloatField()),
            ],
        ),
    ]
