# Generated by Django 2.2 on 2020-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_Condition', '0002_auto_20200608_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='request_time',
            field=models.DateTimeField(verbose_name='请求发出时间'),
        ),
    ]
