# Generated by Django 2.2 on 2020-06-08 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Air_Condition', '0003_auto_20200608_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('room_id', models.IntegerField(verbose_name='发出请求的房间号')),
                ('current_temp', models.IntegerField(verbose_name='目标温度')),
                ('target_temp', models.IntegerField(verbose_name='目标温度')),
                ('fan_speed', models.IntegerField(choices=[(1, 'HIGH'), (2, 'MIDDLE'), (3, 'LOW')], verbose_name='风速')),
                ('fee', models.FloatField(verbose_name='费用')),
            ],
            options={
                'verbose_name': '操作列表',
                'ordering': ('-request_time',),
            },
        ),
    ]
