# Generated by Django 3.0.6 on 2020-06-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_Condition', '0004_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='request_time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='请求发出时间'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='state',
            field=models.IntegerField(choices=[(1, 'WORKING'), (2, 'SHUTDOWN'), (3, 'SETMODE'), (4, 'READY')], default=2, verbose_name='中控机状态'),
        ),
    ]
