# Generated by Django 2.2 on 2020-06-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Air_Condition', '0005_auto_20200609_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-request_time',), 'verbose_name': '操作列表', 'verbose_name_plural': '操作列表'},
        ),
    ]
